// src/jvis/data/stacks/vue-vite/files/src/components/ui/ItemList.vue
<script setup lang="ts">
import type { Item } from '../../types/item';
import ItemCard from './ItemCard.vue';

defineProps<{ items: Item[] }>();
const emit = defineEmits<{ delete: [id: string] }>();
</script>

<template>
  <p v-if="items.length === 0">No items yet. Create one above.</p>
  <ul v-else class="item-list">
    <li v-for="item in items" :key="item.id">
      <ItemCard :item="item" @delete="emit('delete', $event)" />
    </li>
  </ul>
</template>

// src/jvis/data/stacks/svelte-kit/files/src/lib/components/ItemList.svelte
<script lang="ts">
  import type { Item } from '../types/item';
  import ItemCard from './ItemCard.svelte';
  import { createEventDispatcher } from 'svelte';

  export let items: Item[];
  const dispatch = createEventDispatcher<{ delete: string }>();
</script>

{#if items.length === 0}
  <p>No items yet. Create one above.</p>
{:else}
  <ul class="item-list">
    {#each items as item (item.id)}
      <li>
        <ItemCard {item} on:delete />
      </li>
    {/each}
  </ul>
{/if}
