// src/jvis/data/stacks/react-vite/files/src/components/ui/ItemCard.tsx
import { useState } from 'react';
import type { Item } from '../../types/item';

interface ItemCardProps {
  item: Item;
  onDelete: (id: string) => Promise<void>;
}

export function ItemCard({ item, onDelete }: ItemCardProps) {
  const [deleting, setDeleting] = useState(false);

  const handleDelete = async () => {
    setDeleting(true);
    try {
      await onDelete(item.id);
    } catch {
      setDeleting(false);
    }
  };

  return (
    <div className="item-card">
      <h3>{item.name}</h3>
      {item.description && <p>{item.description}</p>}
      <button type="button" onClick={handleDelete} disabled={deleting}>
        {deleting ? 'Deleting...' : 'Delete'}
      </button>
    </div>
  );
}

// src/jvis/data/stacks/svelte-kit/files/src/lib/components/ItemCard.svelte
<script lang="ts">
  import type { Item } from '../types/item';
  import { createEventDispatcher } from 'svelte';

  export let item: Item;

  const dispatch = createEventDispatcher<{ delete: string }>();
  let deleting = false;

  function handleDelete() {
    deleting = true;
    dispatch('delete', item.id);
  }
</script>

<div class="item-card">
  <h3>{item.name}</h3>
  {#if item.description}
    <p>{item.description}</p>
  {/if}
  <button type="button" on:click={handleDelete} disabled={deleting}>
    {deleting ? 'Deleting...' : 'Delete'}
  </button>
</div>
