// src/jvis/data/stacks/svelte-kit/files/src/lib/components/ItemCard.svelte
<script lang="ts">
  import type { Item } from '../types/item';
  import { createEventDispatcher } from 'svelte';

  export let item: Item;

  const dispatch = createEventDispatcher<{ delete: string }>();
  let deleting = false;

  function handleDelete() {
    deleting = true;
    dispatch('delete', item.id);
  }
</script>

<div class="item-card">
  <h3>{item.name}</h3>
  {#if item.description}
    <p>{item.description}</p>
  {/if}
  <button type="button" on:click={handleDelete} disabled={deleting}>
    {deleting ? 'Deleting...' : 'Delete'}
  </button>
</div>

// src/jvis/data/stacks/vue-vite/files/src/components/ui/ItemCard.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { Item } from '../../types/item';

const props = defineProps<{ item: Item }>();
const emit = defineEmits<{ delete: [id: string] }>();

const deleting = ref(false);

async function handleDelete() {
  deleting.value = true;
  emit('delete', props.item.id);
}
</script>

<template>
  <div class="item-card">
    <h3>{{ item.name }}</h3>
    <p v-if="item.description">{{ item.description }}</p>
    <button type="button" @click="handleDelete" :disabled="deleting">
      {{ deleting ? 'Deleting...' : 'Delete' }}
    </button>
  </div>
</template>
