// src/jvis/data/stacks/react-vite/files/src/components/ui/ItemList.tsx
import type { Item } from '../../types/item';
import { ItemCard } from './ItemCard';

interface ItemListProps {
  items: Item[];
  onDelete: (id: string) => void;
}

export function ItemList({ items, onDelete }: ItemListProps) {
  if (items.length === 0) {
    return <p>No items yet. Create one above.</p>;
  }

  return (
    <ul className="item-list">
      {items.map((item) => (
        <li key={item.id}>
          <ItemCard item={item} onDelete={onDelete} />
        </li>
      ))}
    </ul>
  );
}

// src/jvis/data/stacks/vue-vite/files/src/components/ui/ItemList.vue
<script setup lang="ts">
import type { Item } from '../../types/item';
import ItemCard from './ItemCard.vue';

defineProps<{ items: Item[] }>();
const emit = defineEmits<{ delete: [id: string] }>();
</script>

<template>
  <p v-if="items.length === 0">No items yet. Create one above.</p>
  <ul v-else class="item-list">
    <li v-for="item in items" :key="item.id">
      <ItemCard :item="item" @delete="emit('delete', $event)" />
    </li>
  </ul>
</template>
