// src/jvis/data/stacks/vue-vite/files/src/components/ui/ItemList.vue
<script setup lang="ts">
import type { Item } from '../../types/item';
import ItemCard from './ItemCard.vue';

defineProps<{ items: Item[] }>();
const emit = defineEmits<{ delete: [id: string] }>();
</script>

<template>
  <p v-if="items.length === 0">No items yet. Create one above.</p>
  <ul v-else class="item-list">
    <li v-for="item in items" :key="item.id">
      <ItemCard :item="item" @delete="emit('delete', $event)" />
    </li>
  </ul>
</template>

// src/jvis/data/stacks/angular/files/src/app/components/item-list/item-list.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { Item } from '../../models/item.model';
import { ItemCardComponent } from '../item-card/item-card.component';

@Component({
  selector: 'app-item-list',
  standalone: true,
  imports: [ItemCardComponent],
  templateUrl: './item-list.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ItemListComponent {
  @Input({ required: true }) items: Item[] = [];
  @Output() deleteItem = new EventEmitter<string>();
}

@if (items.length === 0) {
  <p>No items yet. Create one above.</p>
} @else {
  <ul class="item-list">
    @for (item of items; track item.id) {
      <li>
        <app-item-card [item]="item" (deleteItem)="deleteItem.emit($event)" />
      </li>
    }
  </ul>
}
