// src/jvis/data/stacks/svelte-kit/files/src/lib/components/ItemForm.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import type { CreateItemInput } from '../types/item';

  const dispatch = createEventDispatcher<{ submit: CreateItemInput }>();
  let name = '';
  let description = '';
  let submitting = false;

  async function handleSubmit() {
    if (!name.trim()) return;
    submitting = true;
    try {
      dispatch('submit', {
        name: name.trim(),
        description: description.trim() || null,
      });
      name = '';
      description = '';
    } finally {
      submitting = false;
    }
  }
</script>

<form on:submit|preventDefault={handleSubmit} class="item-form">
  <input type="text" placeholder="Item name" bind:value={name} required />
  <input type="text" placeholder="Description (optional)" bind:value={description} />
  <button type="submit" disabled={submitting || !name.trim()}>
    {submitting ? 'Creating...' : 'Create Item'}
  </button>
</form>

// src/jvis/data/stacks/astro/files/src/components/ItemForm.tsx
import { useState } from 'preact/hooks';
import type { CreateItemInput } from '../types/item';

interface Props {
  onSubmit: (input: CreateItemInput) => void;
}

export default function ItemForm({ onSubmit }: Props) {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');

  const handleSubmit = (e: Event) => {
    e.preventDefault();
    if (!name.trim()) return;
    onSubmit({ name: name.trim(), description: description.trim() || undefined });
    setName('');
    setDescription('');
  };

  return (
    <form onSubmit={handleSubmit} class="item-form">
      <input
        value={name}
        onInput={(e) => setName((e.target as HTMLInputElement).value)}
        placeholder="Item name"
        required
      />
      <input
        value={description}
        onInput={(e) => setDescription((e.target as HTMLInputElement).value)}
        placeholder="Description (optional)"
      />
      <button type="submit">Add Item</button>
    </form>
  );
}
